#ifndef PPUTL_GEN_H_INCLUDED
#define PPUTL_GEN_H_INCLUDED
#/////                                                                     c++20
#///////////////////////////////////////////////////////////////////////////////
#/// @brief \link PPUTL_GEN PPUTL_GEN\endlink -
#/// generates [0, 256) args using a generator macro function
#/// @file
#//                          __    ___
#//                         /\ \__/\_ \
#//   _____   _____   __  __\ \ ,_\//\ \
#//  /\ '__`\/\ '__`\/\ \/\ \\ \ \/ \ \ \
#//  \ \ \_\ \ \ \_\ \ \ \_\ \\ \ \_ \_\ \_
#//   \ \ ,__/\ \ ,__/\ \____/ \ \__\/\____\
#//    \ \ \   \ \ \   \/___/   \/__/\/____/
#//     \/_/    \/_/
#//
#//  pputl Preprocessor Utilities
#//  Copyright (C) 2020 Justin Collier <m@jpcx.dev>
#//
#//	   This program is free software: you can redistribute it and/or modify
#//	   it under the terms of the GNU General Public License as published by
#//	   the Free Software Foundation, either version 3 of the License, or
#//	   (at your option) any later version.
#//
#//	   This program is distributed in the hope that it will be useful,
#//	   but WITHOUT ANY WARRANTY; without even the internalied warranty of
#//	   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#//	   GNU General Public License for more details.
#//                                                                           //
#//  You should have received a copy of the GNU General Public License       ///
#//  along with this program.  If not, see <https://www.gnu.org/licenses/>. ////
#///////////////////////////////////////////////////////////////////////////////
#
#include "pputl/cat.h"
#
#/// generates [0, 256) args using a generator macro function
#///
#/// @ingroup pputl
#/// @anchor  PPUTL_GEN
#/// @param n   - number of args to generate [0, 256)
#/// @param gen - generator macro function of the form:
#///              f(idx) -> token
#define PPUTL_GEN(n, gen, ...) PPUTL_CAT(PPUTL_DETAIL_GEN_, n)(gen, __VA_ARGS__)
#
#// clang-format off
#define PPUTL_DETAIL_GEN_0(  g, ...)
#define PPUTL_DETAIL_GEN_1(  g, ...)                                        g(0   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_2(  g, ...) PPUTL_DETAIL_GEN_1  (g, __VA_ARGS__), g(1   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_3(  g, ...) PPUTL_DETAIL_GEN_2  (g, __VA_ARGS__), g(2   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_4(  g, ...) PPUTL_DETAIL_GEN_3  (g, __VA_ARGS__), g(3   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_5(  g, ...) PPUTL_DETAIL_GEN_4  (g, __VA_ARGS__), g(4   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_6(  g, ...) PPUTL_DETAIL_GEN_5  (g, __VA_ARGS__), g(5   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_7(  g, ...) PPUTL_DETAIL_GEN_6  (g, __VA_ARGS__), g(6   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_8(  g, ...) PPUTL_DETAIL_GEN_7  (g, __VA_ARGS__), g(7   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_9(  g, ...) PPUTL_DETAIL_GEN_8  (g, __VA_ARGS__), g(8   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_10( g, ...) PPUTL_DETAIL_GEN_9  (g, __VA_ARGS__), g(9   __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_11( g, ...) PPUTL_DETAIL_GEN_10 (g, __VA_ARGS__), g(10  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_12( g, ...) PPUTL_DETAIL_GEN_11 (g, __VA_ARGS__), g(11  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_13( g, ...) PPUTL_DETAIL_GEN_12 (g, __VA_ARGS__), g(12  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_14( g, ...) PPUTL_DETAIL_GEN_13 (g, __VA_ARGS__), g(13  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_15( g, ...) PPUTL_DETAIL_GEN_14 (g, __VA_ARGS__), g(14  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_16( g, ...) PPUTL_DETAIL_GEN_15 (g, __VA_ARGS__), g(15  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_17( g, ...) PPUTL_DETAIL_GEN_16 (g, __VA_ARGS__), g(16  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_18( g, ...) PPUTL_DETAIL_GEN_17 (g, __VA_ARGS__), g(17  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_19( g, ...) PPUTL_DETAIL_GEN_18 (g, __VA_ARGS__), g(18  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_20( g, ...) PPUTL_DETAIL_GEN_19 (g, __VA_ARGS__), g(19  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_21( g, ...) PPUTL_DETAIL_GEN_20 (g, __VA_ARGS__), g(20  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_22( g, ...) PPUTL_DETAIL_GEN_21 (g, __VA_ARGS__), g(21  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_23( g, ...) PPUTL_DETAIL_GEN_22 (g, __VA_ARGS__), g(22  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_24( g, ...) PPUTL_DETAIL_GEN_23 (g, __VA_ARGS__), g(23  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_25( g, ...) PPUTL_DETAIL_GEN_24 (g, __VA_ARGS__), g(24  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_26( g, ...) PPUTL_DETAIL_GEN_25 (g, __VA_ARGS__), g(25  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_27( g, ...) PPUTL_DETAIL_GEN_26 (g, __VA_ARGS__), g(26  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_28( g, ...) PPUTL_DETAIL_GEN_27 (g, __VA_ARGS__), g(27  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_29( g, ...) PPUTL_DETAIL_GEN_28 (g, __VA_ARGS__), g(28  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_30( g, ...) PPUTL_DETAIL_GEN_29 (g, __VA_ARGS__), g(29  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_31( g, ...) PPUTL_DETAIL_GEN_30 (g, __VA_ARGS__), g(30  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_32( g, ...) PPUTL_DETAIL_GEN_31 (g, __VA_ARGS__), g(31  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_33( g, ...) PPUTL_DETAIL_GEN_32 (g, __VA_ARGS__), g(32  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_34( g, ...) PPUTL_DETAIL_GEN_33 (g, __VA_ARGS__), g(33  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_35( g, ...) PPUTL_DETAIL_GEN_34 (g, __VA_ARGS__), g(34  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_36( g, ...) PPUTL_DETAIL_GEN_35 (g, __VA_ARGS__), g(35  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_37( g, ...) PPUTL_DETAIL_GEN_36 (g, __VA_ARGS__), g(36  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_38( g, ...) PPUTL_DETAIL_GEN_37 (g, __VA_ARGS__), g(37  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_39( g, ...) PPUTL_DETAIL_GEN_38 (g, __VA_ARGS__), g(38  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_40( g, ...) PPUTL_DETAIL_GEN_39 (g, __VA_ARGS__), g(39  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_41( g, ...) PPUTL_DETAIL_GEN_40 (g, __VA_ARGS__), g(40  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_42( g, ...) PPUTL_DETAIL_GEN_41 (g, __VA_ARGS__), g(41  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_43( g, ...) PPUTL_DETAIL_GEN_42 (g, __VA_ARGS__), g(42  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_44( g, ...) PPUTL_DETAIL_GEN_43 (g, __VA_ARGS__), g(43  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_45( g, ...) PPUTL_DETAIL_GEN_44 (g, __VA_ARGS__), g(44  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_46( g, ...) PPUTL_DETAIL_GEN_45 (g, __VA_ARGS__), g(45  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_47( g, ...) PPUTL_DETAIL_GEN_46 (g, __VA_ARGS__), g(46  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_48( g, ...) PPUTL_DETAIL_GEN_47 (g, __VA_ARGS__), g(47  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_49( g, ...) PPUTL_DETAIL_GEN_48 (g, __VA_ARGS__), g(48  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_50( g, ...) PPUTL_DETAIL_GEN_49 (g, __VA_ARGS__), g(49  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_51( g, ...) PPUTL_DETAIL_GEN_50 (g, __VA_ARGS__), g(50  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_52( g, ...) PPUTL_DETAIL_GEN_51 (g, __VA_ARGS__), g(51  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_53( g, ...) PPUTL_DETAIL_GEN_52 (g, __VA_ARGS__), g(52  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_54( g, ...) PPUTL_DETAIL_GEN_53 (g, __VA_ARGS__), g(53  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_55( g, ...) PPUTL_DETAIL_GEN_54 (g, __VA_ARGS__), g(54  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_56( g, ...) PPUTL_DETAIL_GEN_55 (g, __VA_ARGS__), g(55  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_57( g, ...) PPUTL_DETAIL_GEN_56 (g, __VA_ARGS__), g(56  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_58( g, ...) PPUTL_DETAIL_GEN_57 (g, __VA_ARGS__), g(57  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_59( g, ...) PPUTL_DETAIL_GEN_58 (g, __VA_ARGS__), g(58  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_60( g, ...) PPUTL_DETAIL_GEN_59 (g, __VA_ARGS__), g(59  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_61( g, ...) PPUTL_DETAIL_GEN_60 (g, __VA_ARGS__), g(60  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_62( g, ...) PPUTL_DETAIL_GEN_61 (g, __VA_ARGS__), g(61  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_63( g, ...) PPUTL_DETAIL_GEN_62 (g, __VA_ARGS__), g(62  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_64( g, ...) PPUTL_DETAIL_GEN_63 (g, __VA_ARGS__), g(63  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_65( g, ...) PPUTL_DETAIL_GEN_64 (g, __VA_ARGS__), g(64  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_66( g, ...) PPUTL_DETAIL_GEN_65 (g, __VA_ARGS__), g(65  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_67( g, ...) PPUTL_DETAIL_GEN_66 (g, __VA_ARGS__), g(66  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_68( g, ...) PPUTL_DETAIL_GEN_67 (g, __VA_ARGS__), g(67  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_69( g, ...) PPUTL_DETAIL_GEN_68 (g, __VA_ARGS__), g(68  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_70( g, ...) PPUTL_DETAIL_GEN_69 (g, __VA_ARGS__), g(69  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_71( g, ...) PPUTL_DETAIL_GEN_70 (g, __VA_ARGS__), g(70  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_72( g, ...) PPUTL_DETAIL_GEN_71 (g, __VA_ARGS__), g(71  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_73( g, ...) PPUTL_DETAIL_GEN_72 (g, __VA_ARGS__), g(72  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_74( g, ...) PPUTL_DETAIL_GEN_73 (g, __VA_ARGS__), g(73  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_75( g, ...) PPUTL_DETAIL_GEN_74 (g, __VA_ARGS__), g(74  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_76( g, ...) PPUTL_DETAIL_GEN_75 (g, __VA_ARGS__), g(75  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_77( g, ...) PPUTL_DETAIL_GEN_76 (g, __VA_ARGS__), g(76  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_78( g, ...) PPUTL_DETAIL_GEN_77 (g, __VA_ARGS__), g(77  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_79( g, ...) PPUTL_DETAIL_GEN_78 (g, __VA_ARGS__), g(78  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_80( g, ...) PPUTL_DETAIL_GEN_79 (g, __VA_ARGS__), g(79  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_81( g, ...) PPUTL_DETAIL_GEN_80 (g, __VA_ARGS__), g(80  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_82( g, ...) PPUTL_DETAIL_GEN_81 (g, __VA_ARGS__), g(81  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_83( g, ...) PPUTL_DETAIL_GEN_82 (g, __VA_ARGS__), g(82  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_84( g, ...) PPUTL_DETAIL_GEN_83 (g, __VA_ARGS__), g(83  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_85( g, ...) PPUTL_DETAIL_GEN_84 (g, __VA_ARGS__), g(84  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_86( g, ...) PPUTL_DETAIL_GEN_85 (g, __VA_ARGS__), g(85  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_87( g, ...) PPUTL_DETAIL_GEN_86 (g, __VA_ARGS__), g(86  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_88( g, ...) PPUTL_DETAIL_GEN_87 (g, __VA_ARGS__), g(87  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_89( g, ...) PPUTL_DETAIL_GEN_88 (g, __VA_ARGS__), g(88  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_90( g, ...) PPUTL_DETAIL_GEN_89 (g, __VA_ARGS__), g(89  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_91( g, ...) PPUTL_DETAIL_GEN_90 (g, __VA_ARGS__), g(90  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_92( g, ...) PPUTL_DETAIL_GEN_91 (g, __VA_ARGS__), g(91  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_93( g, ...) PPUTL_DETAIL_GEN_92 (g, __VA_ARGS__), g(92  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_94( g, ...) PPUTL_DETAIL_GEN_93 (g, __VA_ARGS__), g(93  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_95( g, ...) PPUTL_DETAIL_GEN_94 (g, __VA_ARGS__), g(94  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_96( g, ...) PPUTL_DETAIL_GEN_95 (g, __VA_ARGS__), g(95  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_97( g, ...) PPUTL_DETAIL_GEN_96 (g, __VA_ARGS__), g(96  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_98( g, ...) PPUTL_DETAIL_GEN_97 (g, __VA_ARGS__), g(97  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_99( g, ...) PPUTL_DETAIL_GEN_98 (g, __VA_ARGS__), g(98  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_100(g, ...) PPUTL_DETAIL_GEN_99 (g, __VA_ARGS__), g(99  __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_101(g, ...) PPUTL_DETAIL_GEN_100(g, __VA_ARGS__), g(100 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_102(g, ...) PPUTL_DETAIL_GEN_101(g, __VA_ARGS__), g(101 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_103(g, ...) PPUTL_DETAIL_GEN_102(g, __VA_ARGS__), g(102 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_104(g, ...) PPUTL_DETAIL_GEN_103(g, __VA_ARGS__), g(103 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_105(g, ...) PPUTL_DETAIL_GEN_104(g, __VA_ARGS__), g(104 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_106(g, ...) PPUTL_DETAIL_GEN_105(g, __VA_ARGS__), g(105 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_107(g, ...) PPUTL_DETAIL_GEN_106(g, __VA_ARGS__), g(106 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_108(g, ...) PPUTL_DETAIL_GEN_107(g, __VA_ARGS__), g(107 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_109(g, ...) PPUTL_DETAIL_GEN_108(g, __VA_ARGS__), g(108 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_110(g, ...) PPUTL_DETAIL_GEN_109(g, __VA_ARGS__), g(109 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_111(g, ...) PPUTL_DETAIL_GEN_110(g, __VA_ARGS__), g(110 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_112(g, ...) PPUTL_DETAIL_GEN_111(g, __VA_ARGS__), g(111 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_113(g, ...) PPUTL_DETAIL_GEN_112(g, __VA_ARGS__), g(112 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_114(g, ...) PPUTL_DETAIL_GEN_113(g, __VA_ARGS__), g(113 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_115(g, ...) PPUTL_DETAIL_GEN_114(g, __VA_ARGS__), g(114 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_116(g, ...) PPUTL_DETAIL_GEN_115(g, __VA_ARGS__), g(115 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_117(g, ...) PPUTL_DETAIL_GEN_116(g, __VA_ARGS__), g(116 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_118(g, ...) PPUTL_DETAIL_GEN_117(g, __VA_ARGS__), g(117 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_119(g, ...) PPUTL_DETAIL_GEN_118(g, __VA_ARGS__), g(118 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_120(g, ...) PPUTL_DETAIL_GEN_119(g, __VA_ARGS__), g(119 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_121(g, ...) PPUTL_DETAIL_GEN_120(g, __VA_ARGS__), g(120 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_122(g, ...) PPUTL_DETAIL_GEN_121(g, __VA_ARGS__), g(121 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_123(g, ...) PPUTL_DETAIL_GEN_122(g, __VA_ARGS__), g(122 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_124(g, ...) PPUTL_DETAIL_GEN_123(g, __VA_ARGS__), g(123 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_125(g, ...) PPUTL_DETAIL_GEN_124(g, __VA_ARGS__), g(124 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_126(g, ...) PPUTL_DETAIL_GEN_125(g, __VA_ARGS__), g(125 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_127(g, ...) PPUTL_DETAIL_GEN_126(g, __VA_ARGS__), g(126 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_128(g, ...) PPUTL_DETAIL_GEN_127(g, __VA_ARGS__), g(127 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_129(g, ...) PPUTL_DETAIL_GEN_128(g, __VA_ARGS__), g(128 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_130(g, ...) PPUTL_DETAIL_GEN_129(g, __VA_ARGS__), g(129 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_131(g, ...) PPUTL_DETAIL_GEN_130(g, __VA_ARGS__), g(130 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_132(g, ...) PPUTL_DETAIL_GEN_131(g, __VA_ARGS__), g(131 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_133(g, ...) PPUTL_DETAIL_GEN_132(g, __VA_ARGS__), g(132 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_134(g, ...) PPUTL_DETAIL_GEN_133(g, __VA_ARGS__), g(133 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_135(g, ...) PPUTL_DETAIL_GEN_134(g, __VA_ARGS__), g(134 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_136(g, ...) PPUTL_DETAIL_GEN_135(g, __VA_ARGS__), g(135 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_137(g, ...) PPUTL_DETAIL_GEN_136(g, __VA_ARGS__), g(136 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_138(g, ...) PPUTL_DETAIL_GEN_137(g, __VA_ARGS__), g(137 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_139(g, ...) PPUTL_DETAIL_GEN_138(g, __VA_ARGS__), g(138 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_140(g, ...) PPUTL_DETAIL_GEN_139(g, __VA_ARGS__), g(139 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_141(g, ...) PPUTL_DETAIL_GEN_140(g, __VA_ARGS__), g(140 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_142(g, ...) PPUTL_DETAIL_GEN_141(g, __VA_ARGS__), g(141 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_143(g, ...) PPUTL_DETAIL_GEN_142(g, __VA_ARGS__), g(142 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_144(g, ...) PPUTL_DETAIL_GEN_143(g, __VA_ARGS__), g(143 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_145(g, ...) PPUTL_DETAIL_GEN_144(g, __VA_ARGS__), g(144 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_146(g, ...) PPUTL_DETAIL_GEN_145(g, __VA_ARGS__), g(145 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_147(g, ...) PPUTL_DETAIL_GEN_146(g, __VA_ARGS__), g(146 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_148(g, ...) PPUTL_DETAIL_GEN_147(g, __VA_ARGS__), g(147 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_149(g, ...) PPUTL_DETAIL_GEN_148(g, __VA_ARGS__), g(148 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_150(g, ...) PPUTL_DETAIL_GEN_149(g, __VA_ARGS__), g(149 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_151(g, ...) PPUTL_DETAIL_GEN_150(g, __VA_ARGS__), g(150 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_152(g, ...) PPUTL_DETAIL_GEN_151(g, __VA_ARGS__), g(151 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_153(g, ...) PPUTL_DETAIL_GEN_152(g, __VA_ARGS__), g(152 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_154(g, ...) PPUTL_DETAIL_GEN_153(g, __VA_ARGS__), g(153 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_155(g, ...) PPUTL_DETAIL_GEN_154(g, __VA_ARGS__), g(154 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_156(g, ...) PPUTL_DETAIL_GEN_155(g, __VA_ARGS__), g(155 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_157(g, ...) PPUTL_DETAIL_GEN_156(g, __VA_ARGS__), g(156 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_158(g, ...) PPUTL_DETAIL_GEN_157(g, __VA_ARGS__), g(157 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_159(g, ...) PPUTL_DETAIL_GEN_158(g, __VA_ARGS__), g(158 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_160(g, ...) PPUTL_DETAIL_GEN_159(g, __VA_ARGS__), g(159 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_161(g, ...) PPUTL_DETAIL_GEN_160(g, __VA_ARGS__), g(160 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_162(g, ...) PPUTL_DETAIL_GEN_161(g, __VA_ARGS__), g(161 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_163(g, ...) PPUTL_DETAIL_GEN_162(g, __VA_ARGS__), g(162 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_164(g, ...) PPUTL_DETAIL_GEN_163(g, __VA_ARGS__), g(163 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_165(g, ...) PPUTL_DETAIL_GEN_164(g, __VA_ARGS__), g(164 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_166(g, ...) PPUTL_DETAIL_GEN_165(g, __VA_ARGS__), g(165 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_167(g, ...) PPUTL_DETAIL_GEN_166(g, __VA_ARGS__), g(166 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_168(g, ...) PPUTL_DETAIL_GEN_167(g, __VA_ARGS__), g(167 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_169(g, ...) PPUTL_DETAIL_GEN_168(g, __VA_ARGS__), g(168 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_170(g, ...) PPUTL_DETAIL_GEN_169(g, __VA_ARGS__), g(169 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_171(g, ...) PPUTL_DETAIL_GEN_170(g, __VA_ARGS__), g(170 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_172(g, ...) PPUTL_DETAIL_GEN_171(g, __VA_ARGS__), g(171 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_173(g, ...) PPUTL_DETAIL_GEN_172(g, __VA_ARGS__), g(172 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_174(g, ...) PPUTL_DETAIL_GEN_173(g, __VA_ARGS__), g(173 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_175(g, ...) PPUTL_DETAIL_GEN_174(g, __VA_ARGS__), g(174 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_176(g, ...) PPUTL_DETAIL_GEN_175(g, __VA_ARGS__), g(175 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_177(g, ...) PPUTL_DETAIL_GEN_176(g, __VA_ARGS__), g(176 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_178(g, ...) PPUTL_DETAIL_GEN_177(g, __VA_ARGS__), g(177 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_179(g, ...) PPUTL_DETAIL_GEN_178(g, __VA_ARGS__), g(178 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_180(g, ...) PPUTL_DETAIL_GEN_179(g, __VA_ARGS__), g(179 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_181(g, ...) PPUTL_DETAIL_GEN_180(g, __VA_ARGS__), g(180 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_182(g, ...) PPUTL_DETAIL_GEN_181(g, __VA_ARGS__), g(181 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_183(g, ...) PPUTL_DETAIL_GEN_182(g, __VA_ARGS__), g(182 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_184(g, ...) PPUTL_DETAIL_GEN_183(g, __VA_ARGS__), g(183 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_185(g, ...) PPUTL_DETAIL_GEN_184(g, __VA_ARGS__), g(184 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_186(g, ...) PPUTL_DETAIL_GEN_185(g, __VA_ARGS__), g(185 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_187(g, ...) PPUTL_DETAIL_GEN_186(g, __VA_ARGS__), g(186 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_188(g, ...) PPUTL_DETAIL_GEN_187(g, __VA_ARGS__), g(187 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_189(g, ...) PPUTL_DETAIL_GEN_188(g, __VA_ARGS__), g(188 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_190(g, ...) PPUTL_DETAIL_GEN_189(g, __VA_ARGS__), g(189 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_191(g, ...) PPUTL_DETAIL_GEN_190(g, __VA_ARGS__), g(190 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_192(g, ...) PPUTL_DETAIL_GEN_191(g, __VA_ARGS__), g(191 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_193(g, ...) PPUTL_DETAIL_GEN_192(g, __VA_ARGS__), g(192 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_194(g, ...) PPUTL_DETAIL_GEN_193(g, __VA_ARGS__), g(193 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_195(g, ...) PPUTL_DETAIL_GEN_194(g, __VA_ARGS__), g(194 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_196(g, ...) PPUTL_DETAIL_GEN_195(g, __VA_ARGS__), g(195 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_197(g, ...) PPUTL_DETAIL_GEN_196(g, __VA_ARGS__), g(196 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_198(g, ...) PPUTL_DETAIL_GEN_197(g, __VA_ARGS__), g(197 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_199(g, ...) PPUTL_DETAIL_GEN_198(g, __VA_ARGS__), g(198 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_200(g, ...) PPUTL_DETAIL_GEN_199(g, __VA_ARGS__), g(199 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_201(g, ...) PPUTL_DETAIL_GEN_200(g, __VA_ARGS__), g(200 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_202(g, ...) PPUTL_DETAIL_GEN_201(g, __VA_ARGS__), g(201 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_203(g, ...) PPUTL_DETAIL_GEN_202(g, __VA_ARGS__), g(202 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_204(g, ...) PPUTL_DETAIL_GEN_203(g, __VA_ARGS__), g(203 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_205(g, ...) PPUTL_DETAIL_GEN_204(g, __VA_ARGS__), g(204 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_206(g, ...) PPUTL_DETAIL_GEN_205(g, __VA_ARGS__), g(205 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_207(g, ...) PPUTL_DETAIL_GEN_206(g, __VA_ARGS__), g(206 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_208(g, ...) PPUTL_DETAIL_GEN_207(g, __VA_ARGS__), g(207 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_209(g, ...) PPUTL_DETAIL_GEN_208(g, __VA_ARGS__), g(208 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_210(g, ...) PPUTL_DETAIL_GEN_209(g, __VA_ARGS__), g(209 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_211(g, ...) PPUTL_DETAIL_GEN_210(g, __VA_ARGS__), g(210 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_212(g, ...) PPUTL_DETAIL_GEN_211(g, __VA_ARGS__), g(211 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_213(g, ...) PPUTL_DETAIL_GEN_212(g, __VA_ARGS__), g(212 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_214(g, ...) PPUTL_DETAIL_GEN_213(g, __VA_ARGS__), g(213 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_215(g, ...) PPUTL_DETAIL_GEN_214(g, __VA_ARGS__), g(214 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_216(g, ...) PPUTL_DETAIL_GEN_215(g, __VA_ARGS__), g(215 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_217(g, ...) PPUTL_DETAIL_GEN_216(g, __VA_ARGS__), g(216 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_218(g, ...) PPUTL_DETAIL_GEN_217(g, __VA_ARGS__), g(217 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_219(g, ...) PPUTL_DETAIL_GEN_218(g, __VA_ARGS__), g(218 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_220(g, ...) PPUTL_DETAIL_GEN_219(g, __VA_ARGS__), g(219 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_221(g, ...) PPUTL_DETAIL_GEN_220(g, __VA_ARGS__), g(220 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_222(g, ...) PPUTL_DETAIL_GEN_221(g, __VA_ARGS__), g(221 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_223(g, ...) PPUTL_DETAIL_GEN_222(g, __VA_ARGS__), g(222 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_224(g, ...) PPUTL_DETAIL_GEN_223(g, __VA_ARGS__), g(223 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_225(g, ...) PPUTL_DETAIL_GEN_224(g, __VA_ARGS__), g(224 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_226(g, ...) PPUTL_DETAIL_GEN_225(g, __VA_ARGS__), g(225 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_227(g, ...) PPUTL_DETAIL_GEN_226(g, __VA_ARGS__), g(226 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_228(g, ...) PPUTL_DETAIL_GEN_227(g, __VA_ARGS__), g(227 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_229(g, ...) PPUTL_DETAIL_GEN_228(g, __VA_ARGS__), g(228 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_230(g, ...) PPUTL_DETAIL_GEN_229(g, __VA_ARGS__), g(229 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_231(g, ...) PPUTL_DETAIL_GEN_230(g, __VA_ARGS__), g(230 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_232(g, ...) PPUTL_DETAIL_GEN_231(g, __VA_ARGS__), g(231 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_233(g, ...) PPUTL_DETAIL_GEN_232(g, __VA_ARGS__), g(232 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_234(g, ...) PPUTL_DETAIL_GEN_233(g, __VA_ARGS__), g(233 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_235(g, ...) PPUTL_DETAIL_GEN_234(g, __VA_ARGS__), g(234 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_236(g, ...) PPUTL_DETAIL_GEN_235(g, __VA_ARGS__), g(235 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_237(g, ...) PPUTL_DETAIL_GEN_236(g, __VA_ARGS__), g(236 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_238(g, ...) PPUTL_DETAIL_GEN_237(g, __VA_ARGS__), g(237 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_239(g, ...) PPUTL_DETAIL_GEN_238(g, __VA_ARGS__), g(238 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_240(g, ...) PPUTL_DETAIL_GEN_239(g, __VA_ARGS__), g(239 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_241(g, ...) PPUTL_DETAIL_GEN_240(g, __VA_ARGS__), g(240 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_242(g, ...) PPUTL_DETAIL_GEN_241(g, __VA_ARGS__), g(241 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_243(g, ...) PPUTL_DETAIL_GEN_242(g, __VA_ARGS__), g(242 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_244(g, ...) PPUTL_DETAIL_GEN_243(g, __VA_ARGS__), g(243 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_245(g, ...) PPUTL_DETAIL_GEN_244(g, __VA_ARGS__), g(244 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_246(g, ...) PPUTL_DETAIL_GEN_245(g, __VA_ARGS__), g(245 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_247(g, ...) PPUTL_DETAIL_GEN_246(g, __VA_ARGS__), g(246 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_248(g, ...) PPUTL_DETAIL_GEN_247(g, __VA_ARGS__), g(247 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_249(g, ...) PPUTL_DETAIL_GEN_248(g, __VA_ARGS__), g(248 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_250(g, ...) PPUTL_DETAIL_GEN_249(g, __VA_ARGS__), g(249 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_251(g, ...) PPUTL_DETAIL_GEN_250(g, __VA_ARGS__), g(250 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_252(g, ...) PPUTL_DETAIL_GEN_251(g, __VA_ARGS__), g(251 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_253(g, ...) PPUTL_DETAIL_GEN_252(g, __VA_ARGS__), g(252 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_254(g, ...) PPUTL_DETAIL_GEN_253(g, __VA_ARGS__), g(253 __VA_OPT__(,) __VA_ARGS__)
#define PPUTL_DETAIL_GEN_255(g, ...) PPUTL_DETAIL_GEN_254(g, __VA_ARGS__), g(254 __VA_OPT__(,) __VA_ARGS__)
#// clang-format off
#
#endif
